websites:
  - url: https://www.wikipedia.org
    interval: 10
  - url: https://news.ycombinator.com/
    interval: 15
  - url: https://www.nationalgeographic.com/environment
    interval: 30
    pattern: sustainability
